# -*- coding: utf-8 -*-
"""Random Password Generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13I8udmj5j72a7lz04DG02SBV0eX0hAAO
"""

import random
import string

uppercase = string.ascii_uppercase
lowercase = string.ascii_lowercase
numbers = string.digits
symbols = string.punctuation

def receiveInput(msg):
    length = input(msg)
    if length.isnumeric():
        length = int(length)

    return length

print("Welcome to random password generator!")
print("Let's Start :)\n")

password_length = receiveInput("Enter password length: ")

while not (isinstance(password_length, int) and password_length >= 8 and password_length <= 16):
    password_length = receiveInput("Please enter a number between 8 and 16: ")
       
print("\nPlease answer the following questions with 'y' or 'n' \n")
    
password_settings = [ 
    {"uppercase":   input("uppercase: "),   "data": uppercase},
    {"lowercase":   input("lowercase: "),   "data": lowercase}, 
    {"symbols":     input("symbols: "),     "data": symbols}, 
    {"digits":      input("digits: "),      "data": numbers}
]

character_set = []

flag = False

for l in password_settings:
    d = list(l.values())[0]
    if d == 'y':
        character_set.append(l['data'])
    elif d == "n":
        continue
    else:
        flag = True

if flag == False:
    password = []
    count = len(character_set)

    for i in character_set:
        password.append(random.choice(i))

    final = "".join(character_set)
    password.extend(random.sample(final, password_length - count))
    random.shuffle(password)
    password = "".join(password)

    print(f"\n your password is: {password}")
else:
    print("Please answer the questions with only 'y' or 'n'.")